import * as React from 'react';
import {
    Body,
    Container,
    Head,
    Heading,
    Html,
    Preview,
    Section,
    Text,
    Link,
    Hr,
    Img,
} from '@react-email/components';

interface BaseTemplateProps {
    preview: string;
    title: string;
    children: React.ReactNode;
}

export const BaseTemplate = ({ preview, title, children }: BaseTemplateProps) => (
    <Html>
        <Head />
        <Preview>{preview}</Preview>
        <Body style={main}>
            <Container style={container}>
                <Section style={header}>
                    <Heading style={h1}>{title}</Heading>
                    <Text style={tagline}>Vanguard Substrate // Axiomatic Protocol</Text>
                </Section>

                <Hr style={hr} />

                <Section style={content}>
                    {children}
                </Section>

                <Hr style={hr} />

                <Section style={footer}>
                    <Text style={footerText}>
                        This message was generated by the Sovereign AI Substrate.
                        Integrity check: 0x611V4
                    </Text>
                    <Text style={footerText}>© 2026 Sovereign Boilerplate</Text>
                </Section>
            </Container>
        </Body>
    </Html>
);

const main = {
    backgroundColor: '#050505',
    color: '#ffffff',
    fontFamily: '"SF Mono", "Fira Code", monospace',
    padding: '40px 0',
};

const container = {
    backgroundColor: '#0a0a0a',
    border: '1px solid #1a1a1a',
    borderRadius: '0px',
    margin: '0 auto',
    padding: '40px',
    width: '600px',
};

const header = {
    textAlign: 'center' as const,
};

const h1 = {
    color: '#a855f7', // Default accent
    fontSize: '24px',
    fontWeight: '900',
    letterSpacing: '4px',
    margin: '20px 0',
    textTransform: 'uppercase' as const,
};

const tagline = {
    color: '#333',
    fontSize: '10px',
    fontWeight: 'bold',
    letterSpacing: '2px',
    textTransform: 'uppercase' as const,
};

const content = {
    lineHeight: '1.6',
    padding: '24px 0',
};

const hr = {
    borderColor: '#1a1a1a',
    margin: '20px 0',
};

const footer = {
    textAlign: 'center' as const,
};

const footerText = {
    color: '#444',
    fontSize: '10px',
    letterSpacing: '1px',
    textTransform: 'uppercase' as const,
};

export default BaseTemplate;
