import { Html, Head, Preview, Body, Container, Section, Text, Heading, Link, Img } from '@react-email/components';
import * as React from 'react';

interface VanguardEmailProps {
    heading: string;
    previewText: string;
    message: string;
    ctaText?: string;
    ctaLink?: string;
}

export const VanguardEmail = ({
    heading = "System Notification",
    previewText = "A new message from the Sovereign Substrate",
    message = "This is a secure system update.",
    ctaText = "Access Terminal",
    ctaLink = "https://boiler.click",
}: VanguardEmailProps) => (
    <Html>
        <Head />
        <Preview>{previewText}</Preview>
        <Body style={main}>
            <Container style={container}>
                <Section style={header}>
                    <Text style={logoText}>BOILER™<span style={logoAccent}>//</span></Text>
                </Section>

                <Section style={bodySection}>
                    <Heading style={h1}>{heading}</Heading>

                    <Text style={text}>
                        {message}
                    </Text>

                    {ctaText && ctaLink && (
                        <Section style={buttonContainer}>
                            <Link style={button} href={ctaLink}>
                                {ctaText}
                            </Link>
                        </Section>
                    )}

                    <Text style={disclaimer}>
                        This transmission was generated by the Sovereign architectural node.<br />
                        Integrity uncompromised.
                    </Text>
                </Section>

                <Section style={footer}>
                    <Text style={footerText}>
                        VANGUARD SECURE TRANSPORT<br />
                        © {new Date().getFullYear()} Boiler Labs. All Rights Reserved.
                    </Text>
                </Section>
            </Container>
        </Body>
    </Html>
);

export default VanguardEmail;

// Inline Styles mapped for rigorous email client compatibility

const main = {
    backgroundColor: '#050505',
    fontFamily: '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif',
};

const container = {
    margin: '0 auto',
    padding: '40px 0',
    width: '100%',
    maxWidth: '600px',
};

const header = {
    padding: '20px 40px',
    textAlign: 'center' as const,
};

const logoText = {
    color: '#FFFFFF',
    fontSize: '24px',
    fontWeight: '900',
    letterSpacing: '4px',
    margin: '0',
};

const logoAccent = {
    color: '#A855F7', // Purple-500
};

const bodySection = {
    backgroundColor: '#0A0A0A',
    border: '1px solid #1A1A1A',
    borderRadius: '8px',
    padding: '40px',
    margin: '20px',
};

const h1 = {
    color: '#FFFFFF',
    fontSize: '24px',
    fontWeight: '800',
    letterSpacing: '2px',
    lineHeight: '32px',
    margin: '0 0 24px',
    textTransform: 'uppercase' as const,
};

const text = {
    color: '#A3A3A3', // Gray-400
    fontSize: '14px',
    lineHeight: '24px',
    margin: '0 0 32px',
};

const buttonContainer = {
    textAlign: 'left' as const,
    margin: '0 0 32px',
};

const button = {
    backgroundColor: '#FFFFFF',
    borderRadius: '0px', // Sharp sovereign aesthetic
    color: '#000000',
    display: 'inline-block',
    fontSize: '12px',
    fontWeight: '900',
    letterSpacing: '2px',
    lineHeight: '100%',
    padding: '16px 32px',
    textDecoration: 'none',
    textTransform: 'uppercase' as const,
    border: '1px solid #FFFFFF',
};

const disclaimer = {
    borderTop: '1px solid #1A1A1A',
    color: '#525252', // Gray-600
    fontSize: '10px',
    lineHeight: '16px',
    margin: '32px 0 0',
    paddingTop: '24px',
    textTransform: 'uppercase' as const,
    letterSpacing: '1px',
};

const footer = {
    padding: '20px 40px',
    textAlign: 'center' as const,
};

const footerText = {
    color: '#525252',
    fontSize: '10px',
    lineHeight: '16px',
    margin: '0',
    textTransform: 'uppercase' as const,
    letterSpacing: '2px',
};
